# commons
FROM golang:1.25.4-alpine AS base

WORKDIR /app

COPY services/commons/ ./services/commons/

# gateway service
FROM base AS gateway

WORKDIR /app/services/gateway

COPY services/gateway/go.mod services/gateway/go.sum ./

RUN go mod download

COPY services/gateway/ ./

RUN go install github.com/air-verse/air@latest

CMD [ "air", "-c", ".air.toml"]

# sessions service
FROM base AS sessions

WORKDIR /app/services/sessions

COPY services/sessions/go.mod services/sessions/go.sum ./

RUN go mod download

COPY services/sessions/ ./

RUN go install github.com/air-verse/air@latest

CMD [ "air", "-c", ".air.toml"]